name: removebg
description: "A new Flutter package project."
version: 0.0.1


environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^4.3.0
  onnxruntime: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android: 
        package: com.archiesengupta.removebg
        pluginClass: RemovebgPlugin
      ios:
        pluginClass: RemovebgPlugin
